### ISSUE TITLE
I want to get the Models

### ISSUE THREAD

**Issue by DWR-CMQ** [MorcilloSanz/RendererGL#119]
Hi,Where are the Models? Could you put it in Assests?
![image](https://github.com/MorcilloSanz/RendererGL/assets/73864469/c8c3ec74-202f-4d57-87c9-b9bf9c9337ec)

**Comment by MorcilloSanz** [comment]
https://github.com/MorcilloSanz/RendererGL/issues/111#issue-1984609586
