### ISSUE TITLE
Incorrect Shader Uniform Parameter Usage for Texture Binding in Renderer.cpp

### ISSUE THREAD

**Issue by DoraemonMiku** [MorcilloSanz/RendererGL#120]
Hi there,
In the `Renderer.cpp` file, the line:
```cpp
shaderProgram->uniformInt("materialMaps.diffuseMap", texture->getID() - 1);
```
is currently passing the texture ID directly to the shader uniform. This approach is incorrect because OpenGL requires the shader to use the texture unit (slot) number, not the texture ID. Instead, it should be modified to:
```cpp
shaderProgram->uniformInt("tex", texture->getSlot() - 0x84C0);
```
In this context, `0x84C0` represents `GL_TEXTURE0`, and the change ensures that the shader correctly references the active texture unit. 
https://community.khronos.org/t/why-use-or-define-texture-units-and-what-is-the-mapping-with-uniforms-and-texture-units/106265/2
![image](https://github.com/user-attachments/assets/00c1448d-24fb-4f03-a151-90915ff77801)

OpenGL uses texture units to manage multiple textures. The `glActiveTexture` function sets the active texture unit, and `glBindTexture` binds the texture to this unit. When passing a uniform to the shader, it should specify the texture slot number rather than the texture ID to ensure proper texture sampling.

Chinese: 
在 `Renderer.cpp` 文件中，以下代码：
```cpp
shaderProgram->uniformInt("materialMaps.diffuseMap", texture->getID() - 1);
```
当前直接将纹理 ID 传递给着色器的 uniform。这种方式不正确，因为 OpenGL 要求着色器使用纹理单元（槽）的编号，而不是纹理 ID。因此，应修改为：
```cpp
shaderProgram->uniformInt("tex", texture->getSlot() - 0x84C0);
```
这里的 `0x84C0` 表示 `GL_TEXTURE0`，此修改确保着色器正确引用激活的纹理单元。

OpenGL 使用纹理单元来管理多个纹理。`glActiveTexture` 函数用于设置活动的纹理单元，而 `glBindTexture` 将纹理绑定到该单元。在向着色器传递 uniform 时，应指定纹理单元编号而不是纹理 ID，以确保正确的纹理采样。

**Comment by MorcilloSanz** [comment]
Hello, 

You are right!
I already changed it. 

Thanks for your help.

**Comment by DoraemonMiku** [comment]
Thanks for the quick fix!
